# License plate format configurations by region

regions:
  US:
    name: "United States"
    formats:
      - pattern: "^[A-Z0-9]{2,3}[A-Z0-9]{3,4}$"  # ABC1234, AB123CD
        description: "Standard US format"
      - pattern: "^[A-Z]{3}[0-9]{3}$"  # ABC123
        description: "Three letter, three number"
      - pattern: "^[0-9]{3}[A-Z]{3}$"  # 123ABC
        description: "Three number, three letter"
    character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    min_length: 5
    max_length: 8
    
  EU:
    name: "European Union"
    formats:
      - pattern: "^[A-Z]{2}[0-9]{2}[A-Z]{3}$"  # AB12CDE
        description: "EU standard format"
    character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    min_length: 7
    max_length: 8
    
  UK:
    name: "United Kingdom"  
    formats:
      - pattern: "^[A-Z]{2}[0-9]{2}[A-Z]{3}$"  # AB12CDE
        description: "Current UK format"
      - pattern: "^[A-Z][0-9]{1,3}[A-Z]{3}$"  # A123BCD
        description: "Prefix format"
    character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    excluded_chars: "IQZ"  # Not used in UK plates
    min_length: 6
    max_length: 7

  CA:
    name: "Canada"
    formats:
      - pattern: "^[A-Z]{3}[0-9]{3}$"  # ABC123
        description: "Standard Canadian format"
      - pattern: "^[0-9]{3}[A-Z]{3}$"  # 123ABC  
        description: "Alternative Canadian format"
    character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    min_length: 6
    max_length: 7

  AU:
    name: "Australia"
    formats:
      - pattern: "^[0-9]{3}[A-Z]{3}$"  # 123ABC
        description: "Standard Australian format"
      - pattern: "^[A-Z]{3}[0-9]{3}$"  # ABC123
        description: "Alternative Australian format"
    character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    min_length: 6
    max_length: 6

# Default settings
default_region: "US"

# OCR post-processing rules
post_processing:
  common_misreads:
    "0": ["O", "Q", "D"]
    "1": ["I", "l", "|"]  
    "2": ["Z"]
    "5": ["S"]
    "6": ["G"]
    "8": ["B"]
    "O": ["0", "Q", "D"]
    "I": ["1", "l", "|"]
    "S": ["5"]
    "G": ["6"]
    "B": ["8"]
    "Z": ["2"]
    
  character_cleanup:
    remove_chars: [" ", ".", "-", "_"]
    replace_chars:
      "l": "1"
      "|": "1"
      "o": "0"
      
# Confidence scoring
confidence:
  format_match_bonus: 0.2  # Bonus for matching regional format
  length_penalty: -0.1     # Penalty per character over/under expected
  character_confidence_weight: 0.8  # Weight for individual character confidence